### ISSUE TITLE
All Flags Are Bugged

### ISSUE THREAD

**Issue by dragoon-103** [JFDCamara/Umbra-Spherae-versions#14]
All the flags seem to be bugged and are random based on the neighbours, Salzburg has austrias flaga as example, happens to all titles such as county to enpires.

**Comment by dragoon-103** [comment]
it seems that this bug actually has some slight randomization to the flags aswell, looks like left over remenants of when they thought about custom flags

**Comment by Nukumnehtar** [comment]
That is because I added new landed titles to Japan, and failed to make flags for them, because I currently lack the capability to make art. If you or anyone else can help me out, what needs flags are for the religious heads of Shinto, Koshinto, and Reformed Ainu religions. That should fix the first issue. The main issue I see with flags right now however is why Japan and China both have similar flags. What happened to all the flags in China we had before?

**Comment by dragoon-103** [comment]
Camara did something to the Asian flags and made them have the normal flag instead of dynastic flags for them, and I think I could try to put together some flags for the needed ones

**Comment by Nukumnehtar** [comment]
China and Japan still seem to have dynastic flags, but I have no idea how to turn them off any other way besides religion or culture...

**Comment by dragoon-103** [comment]
The major flag fixup is fixed, but the asian flags are still all wonky from what they were before Nukumnehtar altered the religions.

**Comment by dragoon-103** [comment]
The Asian flags are now fixed, now working on tidying up the religious heads and localizations for the japanese religions
