### ISSUE TITLE
Discusion on Japanese Religions

### ISSUE THREAD

**Issue by dragoon-103** [JFDCamara/Umbra-Spherae-versions#15]
Hello, Nukumnehtar, just wanted to make this "issue" so we can discuss some things about the new additions to the japanese religions.

And the first order of buisness is, what should the title for the heads of the religions be called? I was thinking something basic like, Shinto High Priesthood and basically the same for all the other Japanese religions.

Another thought is, who should have the title of the shinto faith? I was thinking that the head should be a Yamato Emperor of Japan, not sure if this is the intended result but it currently is just some random guy.

and another minor bug is that Shinto has no religous head, but il try and fix that

Not sure if having this is redundant and uneeded, but i think it would be a better idea to discuss things here then on the forums, i get emails about it here ;)

**Comment by Nukumnehtar** [comment]
Sure, no problem. I was just making heads for all religions or the ability to create them mainly because it is a vanilla feature, so I started in Japan. You can mostly follow the system for religious heads used by the vanilla pagan religion heads. As for Shinto, I initially thought about making the Emperors the heads of religion, but I'm rethinking it that it might be better to change it to be like the other pagan religious heads and have to be created first; as historically they had no official leaders. So maybe its best for it to not exist at first like the others. k_shinto in the Japan file should be the religous head for Shinto.

**Comment by dragoon-103** [comment]
ok, i have been looking around with the japanese and shinto stuff, and it seems to not want to recognize that there is even a religous head, i even changed the title to a duchy and nothing happened. Im not the greatest with modding ck2 but i guess i am learning slowly.

**Comment by Nukumnehtar** [comment]
ok, then you probably have to move the title out of de_jure e_japan that means. Just delete k_japan and clone the d_koshinto code to make a d_shinto. I think that might make it work, as no other religious heads are de_jure vassals. I wonder if de_jure vassals can be made for them however...I will test out in the future just for curiosity's sake. The flags for the other two japanese religious rulers could just use their religious icons on their flag. I think it will work best.
